

server:
  port: 1010

#  spring.datasource.url=jdbc:postgresql://localhost:5432/Drugs?currentSchema=public
#  spring.datasource.username=postgres
#  spring.datasource.password=123456
#  spring.datasource.driverClassName=org.postgresql.Driver
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.properties.hibernate.hbm2ddl.auto=update

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://121.196.232.201:5432/cdm?currentSchema=public
    username: postgres
    password: cdm666
  servlet:
    multipart:
      max-file-size: 15360MB
      max-request-size: 15360MB
  mail:
    protocol: smtp
    host: smtp.sina.com
    username: h3321566631@sina.com
    password: e9544fdd7a686d86

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

